### ISSUE TITLE
Add MIMIC-III 

### ISSUE THREAD

**Issue by rudolfjs** [rudolfjs/PostgresMimicImporter#12]
## Issue

Current version does not allow for the import of MIMIC-III data.

## Tasks

- [ ] Add MIMIC-III import to library
- [ ] MIMIC-III will be another database on the Postgres service.
- [ ] Add MIMIC-III import to config
